name: Mirroring

on: [push, delete]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2

    - name: "Install PHP"
      uses: "shivammathur/setup-php@2.4.2"
      with:
        coverage: "none"
        php-version: "7.4"

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        sudo mkdir -p /usr/src/pandoc
        cd /usr/src/pandoc
        sudo wget https://github.com/jgm/pandoc/releases/download/2.9.2/pandoc-2.9.2-1-amd64.deb
        sudo dpkg -i pandoc-2.9.2-1-amd64.deb

    - name: Copy ENV Laravel Configuration for CI
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./src

    - name: Install Dependencies (PHP vendors)
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      working-directory: ./src

    - name: Generate key
      run: php artisan key:generate
      working-directory: ./src

    - name: Execute tests
      run: php artisan test
      working-directory: ./src

  to_gitlab:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2.3.2

    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@git.ueberlab.com:ueberdosis/alldocs.app.git
        ssh_private_key:
          ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
